import type { Metadata } from "next";
import { Outfit as outfit, Ovo as ovo} from "next/font/google";
import "./globals.css";

const Outfit = outfit({

  subsets: ["latin"],weight:["400","500","600","700"]
});

const Ovo = ovo({

  subsets: ["latin"], weight:["400"]
});

export const metadata: Metadata = {
  title: "portfolio website",
  description: "Generated by daniel arega",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Outfit.className} ${Ovo.className} antialiased leading-8 overflow-x-hidden`}
      >
        {children}
      </body>
    </html> 
  );
}
