import type { Metadata } from "next";
import { Outfit, Ovo } from "next/font/google";
import "./globals.css";
const outfit = Outfit({ subsets: ["latin"], weight: ["400", "700"] });
const ovo = Ovo({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "portfolio website",
  description: "Generated by daniel arega",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
     <body
        className={`${outfit.className} antialiased leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white scroll-smooth`}
      >
        {children}
      </body>
    </html> 
  );
}
